AddressBookApp/ViewModels/Contact/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AddressBookApp.ViewModels
{
    public class ContactFormViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "You must provide contact's name")]
        public string Name { get; set; }       
        [Required(ErrorMessage = "You must provide contact's surname")]
        public string Surname { get; set; }               
        public List<EmailViewModel> Emails { get; set; }
        public List<AddressViewModel> Addresses { get; set; }
    }
}

AddressBookApp/ViewModels/Contact/ContactListItemViewModel.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AddressBookApp.ViewModels
{
    public class ContactListItemViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Surname { get; set; }        
        public IEnumerable<EmailViewModel> Emails { get; set; }
        public IEnumerable<AddressViewModel> Addresses { get; set; }
    }
}

AddressBookApp/Controllers/AddressesController.cs
using System.Web.Mvc;
using AddressBookApp.Data.Context;
using AddressBookApp.ViewModels;
using AddressBookApp.Data.Interfaces;
using AddressBookApp.Data.Infrastructure;
using System;

namespace AddressBookApp.Controllers
{
    public class AddressesController : Controller
    {
        private readonly IAddressBookUnitOfWork _unitOfWork;

        public AddressesController(IAddressBookUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }                       

        // GET: Addresses/Create
        public ActionResult Create(int id)
        {                        
            return View(new AddressViewModel
            {
                PersonId = id
            });              
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,PersonId")] AddressViewModel addressViewModel)
        {
            try
            {                
                if (ModelState.IsValid)
                {
                    _unitOfWork.AddressRepository.AddNewAddressToContact(new Address
                    {
                        PersonId = addressViewModel.PersonId,
                        Name = addressViewModel.Name
                    });
                    TempData["SuccessMessage"] = "Address has been successfully added!";
                    _unitOfWork.CommitChanges();
                    return RedirectToAction("Edit", "Contacts", new { id = addressViewModel.PersonId });
                }
                return View(addressViewModel);

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occured while creating new address";
                return View(addressViewModel);
            }
            
        }

        // GET: Addresses/Edit/5
        public ActionResult Edit([Bind(Include = "addressId")] int addressId)
        {
            var addressModel = _unitOfWork.AddressRepository.GetById(addressId);           
            return View(new AddressViewModel
            {
                Id = addressModel.Id,
                Name = addressModel.Name,
                PersonId = addressModel.PersonId
            });
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PersonId")] AddressViewModel addressViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                   _unitOfWork.AddressRepository.UpdateAddress(
                   new Address
                   {
                       Id = addressViewModel.Id,
                       Name = addressViewModel.Name,
                       PersonId = addressViewModel.PersonId
                   });
                    TempData["SuccessMessage"] = "Address has been successfully updated!";
                    _unitOfWork.CommitChanges();
                    return RedirectToAction("Edit", "Contacts", new { id = addressViewModel.PersonId });
                }
                return View(addressViewModel);
            }
                
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occured while updating address";
                return View(addressViewModel);
            }                       
        }
     
        public ActionResult Delete(int addressId)
        {
            var targetAddress = _unitOfWork.AddressRepository.GetById(addressId);
            return PartialView("Partials/Addresses/_DeleteAddressModal", new AddressViewModel
            {
                Id = targetAddress.Id,
                Name = targetAddress.Name,
                PersonId = targetAddress.PersonId
            });
        }
        
        [HttpPost]        
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "Id,PersonId,Name")] AddressViewModel addressViewModel)
        {
            try
            {
                _unitOfWork.AddressRepository.DeleteAddress(addressViewModel.Id);
                _unitOfWork.CommitChanges();
                TempData["SuccessMessage"] = "Address has been successfully deleted";
                return RedirectToAction("Edit", "Contacts", new { id = addressViewModel.PersonId });
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occured while deleting address";
                return RedirectToAction("Edit", "Contacts", new { id = addressViewModel.PersonId });
            }
            
        }
    }
}

AddressBookApp/Controllers/EmailsController.cs
using System.Web.Mvc;
using AddressBookApp.Data.Context;
using AddressBookApp.ViewModels;
using AddressBookApp.Data.Interfaces;
using AddressBookApp.Data.Infrastructure;
using System;

namespace AddressBookApp.Controllers
{
    public class EmailsController : Controller
    {
        private readonly IAddressBookUnitOfWork _unitOfWork;

        public EmailsController(IAddressBookUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        
        public ActionResult Create(int id)
        {
            return View(new EmailViewModel
            {
                PersonId = id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,PersonId")] EmailViewModel emailViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.EmailRepository.AddNewEmailToContact(new Email
                    {
                        PersonId = emailViewModel.PersonId,
                        Name = emailViewModel.Name
                    });
                    _unitOfWork.CommitChanges();
                    TempData["SuccessMessage"] = "New email has been successfully added!";
                    return RedirectToAction("Edit", "Contacts", new { id = emailViewModel.PersonId });
                }
                return View(emailViewModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occured while creating new email";
                return View(emailViewModel);
            }
          
        }
        
        public ActionResult Edit([Bind(Include = "emailId")] int emailId)
        {
            var emailModel = _unitOfWork.EmailRepository.GetById(emailId);            
            return View(new EmailViewModel
            {
                Id = emailModel.Id,
                Name = emailModel.Name,
                PersonId = emailModel.PersonId
            });
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PersonId")] EmailViewModel emailViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.EmailRepository.UpdateEmail(
                    new Email
                    {
                        Id = emailViewModel.Id,
                        Name = emailViewModel.Name,
                        PersonId = emailViewModel.PersonId
                    });
                    _unitOfWork.CommitChanges();
                    TempData["SuccessMessage"] = "Email has been successfully updated!";
                    return RedirectToAction("Edit", "Contacts", new { id = emailViewModel.PersonId });
                }
                return View(emailViewModel);
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An error occured while updating email";
                return View(emailViewModel);
            }           
        }

        // GET: Emails/Delete/5
        public ActionResult Delete(int emailId)
        {
            var targetEmail = _unitOfWork.EmailRepository.GetById(emailId);
            return PartialView("Partials/Emails/_DeleteEmailModal", new EmailViewModel
            {
                Id = targetEmail.Id,
                Name = targetEmail.Name,
                PersonId = targetEmail.PersonId
            });
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "Id,PersonId,Name")] EmailViewModel emailViewModel)
        {
            try
            {
                _unitOfWork.EmailRepository.DeleteEmail(emailViewModel.Id);
                _unitOfWork.CommitChanges();
                TempData["SuccessMessage"] = "Email has been successfully deleted";
                return RedirectToAction("Edit", "Contacts", new { id = emailViewModel.PersonId });
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An error occured while deleting email";
                return RedirectToAction("Edit", "Contacts", new { id = emailViewModel.PersonId });
            }
           
        }
    }
}

AddressBookApp/Views/Shared/Partials/Contacts/Panels/_ContactAddressesPanel.cshtml
@model AddressBookApp.ViewModels.ContactFormViewModel

<div class="col-xs-12 col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            Manage addresses
            <span>
                @Html.ActionLink("Add new", "Create", "Addresses", new { @id = Model.Id },
                                                new
                                                {
                                                    @class = "glyphicon glyphicon-plus"
                                                })
            </span>
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Address</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model.Addresses != null && Model.Addresses.Count() > 0)
                        {
                            foreach (var address in Model.Addresses)
                            {
                                <tr>
                                    <td>
                                        @address.Name
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Addresses", new { addressId = address.Id }, null) |                                       
                                        @Html.ActionLink("Delete", "Delete", "Addresses", new { addressId = address.Id }, new
                                        {
                                            @class = "modal-link"
                                        })
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AddressBookApp/Views/Shared/Partials/Contacts/Panels/_ContactDetailsPanel.cshtml
@model AddressBookApp.ViewModels.ContactFormViewModel

<div class="row margin-top-70">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Contact details</h4>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                            </div>
                        </div>       
                        
                        @{
                            if (Model.Emails != null)
                            {
                                for (int i = 0; i < Model.Emails.Count; i++)
                                {
                                    @Html.HiddenFor(x => Model.Emails[i].Id);
                                    @Html.HiddenFor(x => Model.Emails[i].PersonId);
                                    @Html.HiddenFor(x => Model.Emails[i].Name);
                                }
                            }
                            if (Model.Addresses != null)
                            {
                                for (int i = 0; i < Model.Addresses.Count; i++)
                                {
                                    @Html.HiddenFor(x => Model.Addresses[i].Id);
                                    @Html.HiddenFor(x => Model.Addresses[i].PersonId);
                                    @Html.HiddenFor(x => Model.Addresses[i].Name);
                                }
                            }
                        }

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AddressBookApp/Views/Shared/Partials/Contacts/Panels/_ContactEmailsPanel.cshtml
@model AddressBookApp.ViewModels.ContactFormViewModel

<div class="col-xs-12 col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            Manage emails
            <span>
                @Html.ActionLink("Add new", "Create", "Emails", new { @id = Model.Id },
                                                new
                                                {
                                                    @class = "glyphicon glyphicon-plus"
                                                })
            </span>
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model.Emails != null && Model.Emails.Count() > 0)
                        {
                            foreach (var email in Model.Emails)
                            {
                                <tr>
                                    <td>
                                        @email.Name
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Emails", new { emailId = email.Id }, null) |                                      
                                        @Html.ActionLink("Delete", "Delete", "Emails", new { emailId = email.Id }, new {
                                            @class = "modal-link"
                                        })
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>